name: SignEase
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  syncfusion_flutter_charts: 27.1.57 
  path_provider: ^2.0.11
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  provider: ^6.1.2
  tutorial_coach_mark: ^1.2.11
  animate_do: ^3.3.4
  pdf: ^3.9.1
  fl_chart: ^0.69.0
  animated_text_kit: ^4.2.2
  cloud_firestore: ^5.0.1
  lottie: ^3.1.2
  firebase_database: ^11.0.1
  google_fonts: ^6.2.1
  collection: ^1.18.0
  shared_preferences: ^2.3.2
  mongo_dart: ^0.10.3
  video_player: ^2.1.15
  screenshot: ^3.0.0
  share_plus: ^10.1.1
  printing: ^5.13.4
  chewie: ^1.8.5
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Custom fonts section
  fonts:
    - family: RubikWetPaint
      fonts:
        - asset: fonts/RubikWetPaint-Regular.ttf
    - family: DancingScriptubikWetPaint
      fonts:
        - asset: fonts/DancingScript-VariableFont_wght.ttf

  assets:
    - assets/
    - images/
