// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACSu3jUhSEt2rWSYccdIFS38xIijO_8nw',
    appId: '1:894444876029:web:588df0b07cc91183e20e94',
    messagingSenderId: '894444876029',
    projectId: 'loginsignupapp-7c92a',
    authDomain: 'loginsignupapp-7c92a.firebaseapp.com',
    storageBucket: 'loginsignupapp-7c92a.appspot.com',
    measurementId: 'G-D3MBLDBHP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV_KJLOe5aMGSY6mlg1dAm35wAb1o3bsY',
    appId: '1:894444876029:android:06b09d39536dc425e20e94',
    messagingSenderId: '894444876029',
    projectId: 'loginsignupapp-7c92a',
    storageBucket: 'loginsignupapp-7c92a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhSDYfS5z-M-_-7E1skpJBE6QCtxXxtW4',
    appId: '1:894444876029:ios:0e12ec5362480ce3e20e94',
    messagingSenderId: '894444876029',
    projectId: 'loginsignupapp-7c92a',
    storageBucket: 'loginsignupapp-7c92a.appspot.com',
    iosBundleId: 'com.example.flutterLoginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhSDYfS5z-M-_-7E1skpJBE6QCtxXxtW4',
    appId: '1:894444876029:ios:0e12ec5362480ce3e20e94',
    messagingSenderId: '894444876029',
    projectId: 'loginsignupapp-7c92a',
    storageBucket: 'loginsignupapp-7c92a.appspot.com',
    iosBundleId: 'com.example.flutterLoginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACSu3jUhSEt2rWSYccdIFS38xIijO_8nw',
    appId: '1:894444876029:web:dbb9bd53cecab6b1e20e94',
    messagingSenderId: '894444876029',
    projectId: 'loginsignupapp-7c92a',
    authDomain: 'loginsignupapp-7c92a.firebaseapp.com',
    storageBucket: 'loginsignupapp-7c92a.appspot.com',
    measurementId: 'G-2R3C2Z62JN',
  );
}
